//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Rules_PDF
    {
        public int Rules_PDF_Id { get; set; }
        public string Rules_PDF_Name { get; set; }
        public string Rules_PDF_Path { get; set; }
        public Nullable<System.DateTime> Rules_PDF_Upload_Date { get; set; }
    }
}
