//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_Requests()
        {
            this.cat_Applications = new HashSet<cat_Applications>();
        }
    
        public int Request_Id { get; set; }
        public string Request_Name { get; set; }
        public string Request_JSON_Body { get; set; }
        public System.DateTime Request_Creation_Date { get; set; }
        public System.DateTime Request_Start_Date { get; set; }
        public System.DateTime Request_Finish_Date { get; set; }
        public Nullable<int> Request_Max_Applications { get; set; }
        public Nullable<int> Request_Max_Beneficiaries { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_Applications> cat_Applications { get; set; }
    }
}
