//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Application_Files
    {
        public int Application_File_Id { get; set; }
        public string Application_File_Path { get; set; }
        public string Application_File_Name { get; set; }
        public System.DateTime Application_File_Upload_Date { get; set; }
        public int Application_Id { get; set; }
    
        public virtual cat_Applications cat_Applications { get; set; }
    }
}
