//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Admin_Users
    {
        public int Admin_User_Id { get; set; }
        public string Admin_User_Username { get; set; }
        public byte[] Admin_User_Password { get; set; }
    }
}
