//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Application_Files
    {
        public int Application_File_Id { get; set; }
        public string Application_File_Path { get; set; }
        public string Application_File_Name { get; set; }
        public System.DateTime Application_File_Upload_Date { get; set; }
        public int Application_Id { get; set; }
    
        public virtual cat_Applications cat_Applications { get; set; }
    }
}
