//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_Requests()
        {
            this.cat_Applications = new HashSet<cat_Applications>();
        }
    
        public int Request_Id { get; set; }
        public string Request_Name { get; set; }
        public string Request_JSON_Body { get; set; }
        public System.DateTime Request_Creation_Date { get; set; }
        public System.DateTime Request_Start_Date { get; set; }
        public System.DateTime Request_Finish_Date { get; set; }
        public Nullable<int> Request_Max_Applications { get; set; }
        public Nullable<int> Request_Max_Beneficiaries { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_Applications> cat_Applications { get; set; }
    }
}
