//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Applications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_Applications()
        {
            this.cat_Application_Files = new HashSet<cat_Application_Files>();
        }
    
        public int Application_Id { get; set; }
        public System.DateTime Application_Date { get; set; }
        public System.DateTime Application_Stage_Date { get; set; }
        public int Application_Stage_Id { get; set; }
        public string Application_JSON_Body { get; set; }
        public Nullable<int> Application_Score { get; set; }
        public string Application_Applicant_Name { get; set; }
        public string Application_Applicant_Email { get; set; }
        public string Application_Applicant_Phone { get; set; }
        public string Application_PDF_Path { get; set; }
        public string Application_Applicant_CURP { get; set; }
        public Nullable<int> Request_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_Application_Files> cat_Application_Files { get; set; }
        public virtual cat_Application_Stages cat_Application_Stages { get; set; }
        public virtual cat_Requests cat_Requests { get; set; }
    }
}
