//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Requirements_PDF
    {
        public int Requirements_PDF_Id { get; set; }
        public string Requirements_PDF_Name { get; set; }
        public string Requirements_PDF_Path { get; set; }
        public Nullable<System.DateTime> Requirements_PDF_Upload_Date { get; set; }
    }
}
