//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMS_fefarmEntities : DbContext
    {
        public CMS_fefarmEntities()
            : base("name=CMS_fefarmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_Admin_Users> cat_Admin_Users { get; set; }
        public virtual DbSet<cat_Application_Files> cat_Application_Files { get; set; }
        public virtual DbSet<cat_Applications> cat_Applications { get; set; }
        public virtual DbSet<cat_Evidences_PDF> cat_Evidences_PDF { get; set; }
        public virtual DbSet<cat_Grant_PDF> cat_Grant_PDF { get; set; }
        public virtual DbSet<cat_News_PDF> cat_News_PDF { get; set; }
        public virtual DbSet<cat_Requests> cat_Requests { get; set; }
        public virtual DbSet<cat_Requirements_PDF> cat_Requirements_PDF { get; set; }
        public virtual DbSet<cat_Rules_PDF> cat_Rules_PDF { get; set; }
        public virtual DbSet<cat_Application_Stages> cat_Application_Stages { get; set; }
        public virtual DbSet<vw_Requests> vw_Requests { get; set; }
        public virtual DbSet<vw_OpenRequestTemplates> vw_OpenRequestTemplates { get; set; }
        public virtual DbSet<vw_Applications> vw_Applications { get; set; }
        public virtual DbSet<Error_Logs> Error_Logs { get; set; }
        public virtual DbSet<cat_Duplicated_CURP> cat_Duplicated_CURP { get; set; }
    }
}
