//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMS_fefarmEntities : DbContext
    {
        public CMS_fefarmEntities()
            : base("name=CMS_fefarmEntities")
        {
    		this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_Admin_Users> cat_Admin_Users { get; set; }
        public virtual DbSet<cat_Grant_PDF> cat_Grant_PDF { get; set; }
        public virtual DbSet<cat_Evidences_PDF> cat_Evidences_PDF { get; set; }
        public virtual DbSet<cat_Requirements_PDF> cat_Requirements_PDF { get; set; }
        public virtual DbSet<cat_Rules_PDF> cat_Rules_PDF { get; set; }
    }
}
