//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Applications
    {
        public int Application_Id { get; set; }
        public Nullable<int> Application_Score { get; set; }
        public string Application_Applicant_Name { get; set; }
        public string Application_Applicant_Email { get; set; }
        public string Application_Applicant_Phone { get; set; }
        public string Application_PDF_Path { get; set; }
        public string Application_Date { get; set; }
        public int Application_Stage_Id { get; set; }
        public string Application_Stage_Name { get; set; }
        public string Application_Applicant_CURP { get; set; }
        public Nullable<int> Request_Id { get; set; }
    }
}
