//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.fefarm.mx.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Requests
    {
        public int Request_Id { get; set; }
        public string Request_Name { get; set; }
        public string Request_JSON_Body { get; set; }
        public string Request_Creation_Date { get; set; }
        public string Request_Start_Date { get; set; }
        public string Request_Finish_Date { get; set; }
        public Nullable<int> Request_Max_Applications { get; set; }
        public Nullable<int> Request_Max_Beneficiaries { get; set; }
    }
}
